#!/usr/bin/env bash

rm -rf /autograder/source/STUDENT-SOLUTION-1/solution.cpp

cp /autograder/submission/*.cpp /autograder/source/STUDENT-SOLUTION-1/solution.cpp

cd /autograder/source

chmod u+x ./MAKE-REFERENCE.sh
./MAKE-REFERENCE.sh

chmod u+x ./grade.sh
./grade.sh STUDENT-SOLUTION-1/