#!/usr/bin/env bash

cp /autograder/submission/solution.cpp /autograder/source/STUDENT-SOLUTION-1

cd /autograder/source

chmod u+x ./MAKE-REFERENCE.sh
./MAKE-REFERENCE.sh

chmod u+x ./grade.sh
./grade.sh STUDENT-SOLUTION-1/