BINARIES= solution

all:	${BINARIES}

sol: sol.cpp
	g++ -std=c++11 sol.cpp -o sol

solution: solution.cpp
	g++ -std=c++11 solution.cpp -o solution

helloConsole: helloConsole.cpp
	g++ -std=c++11 helloConsole.cpp -o helloConsole

helloFile: helloFile.cpp
	g++ -std=c++11 helloFile.cpp -o helloFile

clean:
	/bin/rm -rf *.o ${BINARIES}